# Generated by Django 5.1.6 on 2025-02-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Фото')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('position', models.CharField(max_length=100, verbose_name='Позиция')),
                ('social_media_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на СС')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Шеф повар',
                'verbose_name_plural': 'Шеф повара',
            },
        ),
    ]
