# Generated by Django 5.1.6 on 2025-03-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Почта')),
                ('time', models.DateTimeField(verbose_name='Дата и время')),
                ('people', models.IntegerField(max_length=2, verbose_name='Количество людей')),
                ('request', models.TextField(verbose_name='Особые предпочтения')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
            },
        ),
    ]
