# Generated by Django 5.1.6 on 2025-03-14 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_booking_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=models.EmailField(max_length=100, null=True, unique=True, verbose_name='Электронная почта'),
        ),
    ]
